# Use the official RabbitMQ image as the base image
FROM rabbitmq:management

# Expose the ports required by RabbitMQ
EXPOSE 5672 15672

# (Optional) Set environment variables for RabbitMQ configuration
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=admin123